runtime: php82
service: default

env_variables:
  GOOGLE_CLOUD_PROJECT_ID: "lokalook-id"
  GOOGLE_CLOUD_KEY_FILE: "service-account.json"
  GOOGLE_CLOUD_STORAGE_BUCKET: "lokalook-web-api"

handlers:
  - url: /static
    static_dir: public

  - url: /.*
    script: auto